sm8150-common: Add shim for missing symbol in libcacao_client.so
Fixes:
	java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNK7android6Parcel10readIntPtrEv" referenced by "/system/lib64/libcacao_client.so"...
	java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN7android7SurfaceC1ERKNS_2spINS_22IGraphicBufferProducerEEEb" referenced by "/system/lib64/libcacao_client.so"...