sm8150-common: secd: Version 1.1
Update secd to version 1.1.

ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.somc.hardware.security.secd@1.0::IDeviceSecurity/default
Suggested fix:
Update deprecated HALs to the latest version.
Check for any typos in device manifest or framework compatibility matrices with FCM version >= 6.
For new platform HALs, add them to any framework compatibility matrix with FCM version >= 6 where applicable.
For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.
For android.* HALs that are using unexpected instance names, the instance names need to be added to the AOSP framework compatibility matrices. A regex wildcard can be used if the instance names are proprietary.
: Success